import { ContadorProvider } from '@/data/contexts/ContadorContext'
import { ProdutosProvider } from '@/data/contexts/ProdutosContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProdutosProvider>
      <ContadorProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
          </body>
        </html>
      </ContadorProvider>
    </ProdutosProvider>
  )
}
